import React from 'react';

export const metadata = {
    title: "Activity",
    description: "Generated by create next app",
};

const StatsPage
    = () => {
        return (
            <div>
                Stats are here
            </div>
        );
    };

export default StatsPage
    ;