import React from 'react';


export const metadata = {
    title: "Time-Line",
    description: "Generated by create next app",
};

const TimeLine = () => {
    return (
        <div>
            this is Time line
        </div>
    );
};

export default TimeLine;