import React from 'react';

export const metadata = {
    title: "Friend Home",
    description: "Generated by create next app",
};

const HomePage = () => {
    return (
        <div>
            this is Home page
        </div>
    );
};

export default HomePage;