import Image from "next/image";
import { notFound } from "next/navigation";

import { LuArchive } from "react-icons/lu";
import { MdDeleteForever, MdOutlineSnooze } from "react-icons/md";
import QuickActions from "@/components/QuickActions";



export const metadata = {
    title: "Details",
    description: "Generated by create next app",
};

// Fetch Data
const friendsPromise = async () => {
    const res = await fetch("https://keen-keeper-coral.vercel.app/data.json", {

        cache: 'no-store'
    })
    const data = await res.json();


    return data;
};




export default async function DetailsPage({ params }) {
    const { detailsid } = await params;

    const friends = await friendsPromise();

    const friend = friends.find(
        (f) => Number(f.id) === Number(detailsid)
    );

    if (!friend) return notFound();

    return (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 p-8 w-5xl mx-auto">

            {/* LEFT SIDE */}
            <div >

                <div className="bg-white border border-zinc-200 shadow-md rounded-xl p-6 text-center">

                    <Image
                        src={friend.picture}
                        alt={friend.name}
                        width={64}
                        height={64}
                        className="w-24 h-24 rounded-full mx-auto object-cover"
                    />

                    <h2 className="text-xl font-bold mt-3">
                        {friend.name}
                    </h2>

                    <p className={`mt-2 font-semibold 
                    ${friend.status === "overdue"
                            ? "bg-red-500 text-sm text-white w-fit p-1 rounded-lg flex mx-auto"
                            : ""
                        }  ${friend.status === "almost due"
                            ? "bg-yellow-500 text-sm text-white w-fit p-1 rounded-lg flex mx-auto"
                            : ""
                        }  ${friend.status === "on-track"
                            ? "bg-green-500 text-sm text-white w-fit p-1 rounded-lg flex mx-auto"
                            : ""
                        }`}>
                        {friend.status}
                    </p>

                    <div className="flex flex-wrap justify-center gap-2 mt-3">
                        {friend.tags?.map((tag, i) => (
                            <span
                                key={i}
                                className="bg-green-50 px-2 py-1 rounded-xl text-xs"
                            >
                                {tag}
                            </span>
                        ))}
                    </div>

                    <p className="mt-3 text-gray-500">
                        {friend.bio}
                    </p>

                    <p className="mt-2 text-sm">
                        {friend.email}
                    </p>
                </div>

                <div className="mt-4 flex flex-col gap-2">
                    <button className="btn p-2 rounded">
                        <MdOutlineSnooze size={22} /> Snooze 2 Weeks
                    </button>
                    <button className="btn p-2 rounded">
                        <LuArchive size={22} /> Archive
                    </button>
                    <button className="btn text-[16px]  text-red-600 p-2 rounded">
                        <MdDeleteForever size={22} /> Delete
                    </button>
                </div>
            </div>

            {/* RIGHT SIDE */}
            <div className="lg:col-span-2 flex flex-col gap-6 ">

                <div className="grid grid-cols-3 gap-4">
                    <div className="bg-white  border border-zinc-200 p-4 shadow rounded-xl text-center h-32 items-center justify-center flex-col flex ">
                        <span className="text-3xl font-bold text-[#308764]">{friend.days_since_contact} </span> <br />
                        <span className="text-sm text-gray-500">Days Since Contact</span>
                    </div>
                    <div className="bg-white  border border-zinc-200 p-4 shadow rounded-xl text-center h-32 items-center justify-center flex-col flex ">
                        <span className="text-3xl font-bold text-[#308764]">{friend.goal}</span> <br />
                        <span className="text-sm text-gray-500">Goal (Days)</span>
                    </div>
                    <div className="bg-white  border border-zinc-200 p-4 shadow rounded-xl text-center h-32 items-center justify-center flex-col flex ">
                        <span className="text-3xl font-bold text-[#308764]">  {friend.next_due_date}</span> <br />
                        <span className="text-sm text-gray-500">Next Due</span>
                    </div>
                </div>

                <div className="bg-white p-4 border border-zinc-200 shadow rounded-xl flex justify-between">
                    <div>
                        <h3 className="font-semibold text-[#308764]">
                            Relationship Goal
                        </h3>
                        <p>Connect every <span className="font-bold">{friend.goal} days</span></p>
                    </div>

                    <div>
                        <button className="btn  h-7 font-semibold">Edit</button>
                    </div>
                </div>


                <div className="bg-white p-4 border border-zinc-200 shadow rounded-xl">
                    <div>
                        <h3>Quick Check-In</h3>
                    </div>

                    <QuickActions friend={friend} />
                </div>

                {/* <div className="bg-white p-4 border border-zinc-200 shadow rounded-xl">
                    <div>
                        <h3>
                            Quick Check-In
                        </h3>
                    </div>
                    <div className="p-4 flex gap-4">
                        <button className="btn text-black h-32 w-44 py-2 rounded-xl flex flex-col text-lg">
                            <IoCallOutline size={40} />

                            Call
                        </button>
                        <button className="btn text-black h-32 w-44 py-2 rounded-xl flex flex-col text-lg">
                            <MdOutlineTextsms size={40} /> Text
                        </button>
                        <button className="btn text-black h-32 w-44 py-2 rounded-xl flex flex-col text-lg">
                            <IoVideocamOutline size={40} /> Video
                        </button>
                    </div>
                </div> */}

            </div>
        </div>
    );
}