import Image from "next/image";
import { notFound } from "next/navigation";

import { LuArchive } from "react-icons/lu";
import { MdDeleteForever, MdOutlineSnooze } from "react-icons/md";
import QuickActions from "@/components/QuickActions";

export const metadata = {
    title: "Details",
    description: "Generated by create next app",
};

// Fetch Data
const friendsPromise = async () => {
    const res = await fetch("https://keen-keeper-coral.vercel.app/data.json", {
        cache: "no-store",
    });
    const data = await res.json();
    return data;
};

export default async function DetailsPage({ params }) {
    const { detailsid } = await params;

    const friends = await friendsPromise();

    const friend = friends.find(
        (f) => Number(f.id) === Number(detailsid)
    );

    if (!friend) return notFound();

    return (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 p-4 sm:p-8 w-full max-w-5xl mx-auto">


            <div>
                <div className="bg-white border border-zinc-200 shadow-md rounded-xl p-4 sm:p-6 text-center">

                    <Image
                        src={friend.picture}
                        alt={friend.name}
                        width={64}
                        height={64}
                        className="w-20 h-20 sm:w-24 sm:h-24 rounded-full mx-auto object-cover"
                    />

                    <h2 className="text-lg sm:text-xl font-bold mt-3">
                        {friend.name}
                    </h2>

                    <p
                        className={`mt-2 font-semibold text-sm w-fit mx-auto p-1 rounded-lg ${friend.status === "overdue"
                            ? "bg-red-500 text-white"
                            : ""
                            } ${friend.status === "almost due"
                                ? "bg-yellow-500 text-white"
                                : ""
                            } ${friend.status === "on-track"
                                ? "bg-green-500 text-white"
                                : ""
                            }`}
                    >
                        {friend.status}
                    </p>

                    <div className="flex flex-wrap justify-center gap-2 mt-3">
                        {friend.tags?.map((tag, i) => (
                            <span
                                key={i}
                                className="bg-green-50 px-2 py-1 rounded-xl text-xs"
                            >
                                {tag}
                            </span>
                        ))}
                    </div>

                    <p className="mt-3 text-gray-500 text-sm sm:text-base">
                        {friend.bio}
                    </p>

                    <p className="mt-2 text-sm break-all">
                        {friend.email}
                    </p>
                </div>

                <div className="mt-4 flex flex-col gap-2">
                    <button className="btn p-2 rounded flex items-center justify-center gap-2">
                        <MdOutlineSnooze size={22} /> Snooze 2 Weeks
                    </button>
                    <button className="btn p-2 rounded flex items-center justify-center gap-2">
                        <LuArchive size={22} /> Archive
                    </button>
                    <button className="btn text-[16px] text-red-600 p-2 rounded flex items-center justify-center gap-2">
                        <MdDeleteForever size={22} /> Delete
                    </button>
                </div>
            </div>


            <div className="lg:col-span-2 flex flex-col gap-6">

                <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                    <div className="bg-white border border-zinc-200 p-4 shadow rounded-xl text-center h-32 flex flex-col items-center justify-center">
                        <span className="text-2xl sm:text-3xl font-bold text-[#308764]">
                            {friend.days_since_contact}
                        </span>
                        <span className="text-sm text-gray-500">
                            Days Since Contact
                        </span>
                    </div>

                    <div className="bg-white border border-zinc-200 p-4 shadow rounded-xl text-center h-32 flex flex-col items-center justify-center">
                        <span className="text-2xl sm:text-3xl font-bold text-[#308764]">
                            {friend.goal}
                        </span>
                        <span className="text-sm text-gray-500">
                            Goal (Days)
                        </span>
                    </div>

                    <div className="bg-white border border-zinc-200 p-4 shadow rounded-xl text-center h-32 flex flex-col items-center justify-center">
                        <span className="text-sm sm:text-base font-bold text-[#308764] break-all">
                            {friend.next_due_date}
                        </span>
                        <span className="text-sm text-gray-500">
                            Next Due
                        </span>
                    </div>
                </div>

                <div className="bg-white p-4 border border-zinc-200 shadow rounded-xl flex flex-col sm:flex-row justify-between gap-3">
                    <div>
                        <h3 className="font-semibold text-[#308764]">
                            Relationship Goal
                        </h3>
                        <p>
                            Connect every{" "}
                            <span className="font-bold">
                                {friend.goal} days
                            </span>
                        </p>
                    </div>

                    <div>
                        <button className="btn h-7 font-semibold w-full sm:w-auto">
                            Edit
                        </button>
                    </div>
                </div>

                <div className="bg-white p-4 border border-zinc-200 shadow rounded-xl">
                    <h3>Quick Check-In</h3>
                    <QuickActions friend={friend} />
                </div>

            </div>
        </div>
    );
}