import React from 'react';

export const metadata = {
    title: "Friends Details",
    description: "Generated by create next app",
};

const DetailsPage = async ({ params }) => {
    const p = await params;
    console.log(p);

    return (
        <div>
            Friend details
        </div>
    );
};

export default DetailsPage;